/**
 * Stats Utility Module
 *
 * This module provides utilities for working with tool and tag statistics.
 * It uses the pre-built static data from data/tool-stats.json and data/tag-stats.json
 * (generated by scripts/build-data.ts).
 *
 * This replaces the old utils-api/toolStats.ts which fetched from GitHub at runtime.
 */

import { ToolsByLanguage, Tool } from '@components/tools/types';
import {
    getStaticToolStats,
    getStaticTagStats,
    getStaticTools,
} from './static-data';
import { isSingleLanguageTool } from './filters';
import { sortByVote } from './votes';
import type { StatsApiData, VotesApiData } from './types';
import { mergeToolsWithVotes } from './tools-with-votes';

/**
 * Get tool stats (view counts)
 *
 * @returns Object mapping tool IDs to view counts
 */
export function getToolStats(): StatsApiData {
    return getStaticToolStats();
}

/**
 * Get tag/language stats (view counts)
 *
 * @returns Object mapping tag names to view counts
 */
export function getTagStats(): StatsApiData {
    return getStaticTagStats();
}

/**
 * Get language stats formatted for the homepage
 * Returns languages sorted by views with empty formatter/linter arrays
 *
 * @returns ToolsByLanguage object
 */
export function getLanguageStats(): ToolsByLanguage {
    const tagStats = getStaticTagStats();

    const sortedLanguageStats: ToolsByLanguage = Object.entries(tagStats)
        .sort(([, a], [, b]) => b - a)
        .reduce(
            (r, [key, value]) => ({
                ...r,
                [key]: {
                    views: value,
                    formatters: [],
                    linters: [],
                },
            }),
            {},
        );

    return sortedLanguageStats;
}

/**
 * Get popular languages with their top tools
 * This is used on the homepage to show popular languages and their best tools
 *
 * @param votes - Optional votes data to merge with tools
 * @returns ToolsByLanguage with formatters and linters populated
 */
export function getPopularLanguageStats(
    votes?: VotesApiData | null,
): ToolsByLanguage {
    const tools = getStaticTools();
    const languageStats = getLanguageStats();

    // Merge votes if provided
    const toolsWithVotes = votes ? mergeToolsWithVotes(tools, votes) : tools;

    // Populate formatters and linters for each language
    Object.keys(toolsWithVotes).forEach((toolId) => {
        const tool = toolsWithVotes[toolId];

        if (isSingleLanguageTool(tool)) {
            const language = tool.languages[0];

            if (languageStats[language]) {
                const toolObj: Tool = {
                    id: toolId,
                    ...tool,
                    votes: tool.votes || 0,
                };

                if (tool.categories.includes('formatter')) {
                    languageStats[language].formatters.push(toolObj);
                }
                if (tool.categories.includes('linter')) {
                    languageStats[language].linters.push(toolObj);
                }

                // Sort by votes after pushing tools
                languageStats[language].formatters.sort(sortByVote);
                languageStats[language].linters.sort(sortByVote);

                // Keep top 3
                if (languageStats[language].formatters.length > 3) {
                    languageStats[language].formatters.pop();
                }
                if (languageStats[language].linters.length > 3) {
                    languageStats[language].linters.pop();
                }
            }
        }
    });

    // Filter out languages with no tools
    Object.keys(languageStats).forEach((language) => {
        if (
            languageStats[language].formatters.length === 0 &&
            languageStats[language].linters.length === 0
        ) {
            delete languageStats[language];
        }
    });

    return languageStats;
}

/**
 * Get most viewed tools
 *
 * @param votes - Optional votes data to merge with tools
 * @returns Array of tools sorted by views
 */
export function getMostViewedTools(votes?: VotesApiData | null): Tool[] {
    const tools = getStaticTools();
    const toolStats = getStaticToolStats();

    // Merge votes if provided
    const toolsWithVotes = votes ? mergeToolsWithVotes(tools, votes) : tools;

    const mostViewedToolIds = Object.keys(toolStats);

    const mostViewedTools = mostViewedToolIds
        .map((id) => {
            const tool = toolsWithVotes[id];
            if (!tool) {
                return null;
            }

            return {
                id,
                ...tool,
                votes: tool.votes || 0,
                views: toolStats[id],
            } as Tool & { views: number };
        })
        .filter((tool): tool is Tool & { views: number } => tool !== null);

    return mostViewedTools;
}

/**
 * Get view count for a specific tool
 *
 * @param toolId - The tool ID
 * @returns View count or 0 if not found
 */
export function getToolViewCount(toolId: string): number {
    const stats = getStaticToolStats();
    return stats[toolId] || 0;
}

/**
 * Get view count for a specific tag
 *
 * @param tag - The tag name
 * @returns View count or 0 if not found
 */
export function getTagViewCount(tag: string): number {
    const stats = getStaticTagStats();
    return stats[tag] || 0;
}
