/**
 * Tags Utility Module
 *
 * This module provides utilities for working with tags (languages and others).
 * It uses the pre-built static data from data/tags.json (generated by scripts/build-data.ts)
 * and local data files for descriptions.
 *
 * This replaces the old utils-api/tags.ts which fetched from GitHub at runtime.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { getStaticTags, getStaticTools } from './static-data';
import { isLanguageData } from './type-guards';
import type { TagsType, LanguageData, ApiTag } from './types';

/**
 * Local file path for language/tag description data
 */
const DESCRIPTIONS_PATH = join(process.cwd(), 'data', 'descriptions.json');
const RELATED_TAGS_PATH = join(process.cwd(), 'data', 'relatedTags.json');

/**
 * Get tags from static data
 *
 * @param type - 'languages', 'other', or 'all'
 * @returns Array of tag objects
 */
export function getTags(type: TagsType): ApiTag[] {
    const staticTags = getStaticTags();

    // Build tag objects from the static tags arrays
    const languageTags: ApiTag[] = staticTags.languages.map((lang) => ({
        name: capitalizeFirstLetter(lang),
        value: lang,
        tag_type: 'languages',
    }));

    const otherTags: ApiTag[] = staticTags.others.map((other) => ({
        name: capitalizeFirstLetter(other),
        value: other,
        tag_type: 'other',
    }));

    switch (type) {
        case 'languages':
            return languageTags;
        case 'other':
            return otherTags;
        case 'all':
            return [...languageTags, ...otherTags];
        default:
            console.error(`Unknown tag type: ${type}`);
            return [];
    }
}

/**
 * Get a single tag by type and ID
 */
export function getTag(type: TagsType, tagId: string): ApiTag | null {
    const tags = getTags(type);
    return (
        tags.find((t) => t.value.toLowerCase() === tagId.toLowerCase()) || null
    );
}

/**
 * Get all unique tags from tools data
 * This is useful when you need fresh tag data directly from tools
 */
export function getTagsFromTools(): { languages: string[]; others: string[] } {
    const tools = getStaticTools();
    const languages = new Set<string>();
    const others = new Set<string>();

    for (const tool of Object.values(tools)) {
        tool.languages?.forEach((lang) => languages.add(lang));
        tool.other?.forEach((other) => others.add(other));
    }

    return {
        languages: Array.from(languages).sort(),
        others: Array.from(others).sort(),
    };
}

/**
 * Get language/tag data (description, website, etc.)
 *
 * @param tagId - The tag identifier (e.g., 'javascript', 'python')
 * @returns Language data object with name, website, and description
 */
export function getLanguageData(tagId: string): LanguageData {
    const defaultTagData: LanguageData = {
        name: capitalizeFirstLetter(tagId),
        website: '',
        description: '',
    };

    try {
        if (!existsSync(DESCRIPTIONS_PATH)) {
            return defaultTagData;
        }

        const fileContents = readFileSync(DESCRIPTIONS_PATH, 'utf-8');
        const data = JSON.parse(fileContents);

        if (!data || !data[tagId] || !isLanguageData(data[tagId])) {
            return defaultTagData;
        }

        return data[tagId];
    } catch (error) {
        console.error('Error loading language data:', error);
        return defaultTagData;
    }
}

/**
 * Get similar/related tags for a given tag
 *
 * @param tag - The tag to find related tags for
 * @returns Array of related tag strings
 */
export function getSimilarTags(tag: string): string[] {
    try {
        if (!existsSync(RELATED_TAGS_PATH)) {
            return [];
        }

        const data = readFileSync(RELATED_TAGS_PATH, 'utf-8');
        const relatedTags: string[][] = JSON.parse(data) || [];

        // Find the array that contains the tag
        const relatedTagsArray = relatedTags.find((tags) =>
            tags.includes(tag.toLowerCase()),
        );

        if (!relatedTagsArray) {
            return [];
        }

        // Remove the current tag from the array
        return relatedTagsArray.filter((t) => t !== tag.toLowerCase());
    } catch (error) {
        console.error('Error loading related tags:', error);
        return [];
    }
}

/**
 * Get count of tools for each tag
 *
 * @param type - 'languages' or 'other'
 * @returns Map of tag to tool count
 */
export function getTagCounts(type: 'languages' | 'other'): Map<string, number> {
    const tools = getStaticTools();
    const counts = new Map<string, number>();

    for (const tool of Object.values(tools)) {
        const tags = type === 'languages' ? tool.languages : tool.other;
        tags?.forEach((tag) => {
            counts.set(tag, (counts.get(tag) || 0) + 1);
        });
    }

    return counts;
}

/**
 * Get tags sorted by tool count (most popular first)
 */
export function getPopularTags(
    type: 'languages' | 'other',
    limit?: number,
): Array<{ tag: string; count: number }> {
    const counts = getTagCounts(type);
    const sorted = Array.from(counts.entries())
        .map(([tag, count]) => ({ tag, count }))
        .sort((a, b) => b.count - a.count);

    return limit ? sorted.slice(0, limit) : sorted;
}

/**
 * Helper to capitalize first letter of a string
 */
function capitalizeFirstLetter(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
}
