/**
 * Tools Utility Module
 *
 * This module provides utilities for working with tools data.
 * It uses the pre-built static data from data/tools.json (generated by scripts/build-data.ts)
 * and optionally enriches it with votes from Firebase.
 *
 * This replaces the old utils-api/tools.ts which fetched from GitHub at runtime.
 */

import { getStaticTools, getStaticTool, getStaticToolIds } from './static-data';
import type { ToolsApiData, ApiTool } from './types';
import { Tool } from '@components/tools/types';
import * as fs from 'fs';

/**
 * Get all tools from static data
 * This is the replacement for the old getAllTools() from utils-api/tools.ts
 */
export function getAllTools(): ToolsApiData {
    return getStaticTools();
}

/**
 * Get a single tool by ID
 * This is the replacement for the old getTool() from utils-api/tools.ts
 *
 * Note: This returns the basic tool data without GitHub stats or star history.
 * Those enrichments can be added separately if needed.
 */
export function getTool(toolId: string): Tool | null {
    const tool = getStaticTool(toolId);
    if (!tool) {
        return null;
    }

    // Return tool with id added (matching the expected Tool interface)
    return {
        ...tool,
        id: toolId,
        votes: tool.votes || 0,
    } as Tool;
}

/**
 * Get all tool IDs
 * Useful for generating static paths
 */
export function getAllToolIds(): string[] {
    return getStaticToolIds();
}

/**
 * Check if there is an icon for the tool
 */
export function getToolIcon(toolId: string): string | null {
    // Get the absolute path to the icon from project root
    const iconPath = `${process.cwd()}/public/assets/images/tools/${toolId}.png`;
    if (fs.existsSync(iconPath)) {
        // Return web-accessible path
        return `/assets/images/tools/${toolId}.png`;
    }
    return null;
}

/**
 * Get tools as an array (with IDs included in each tool object)
 */
export function getToolsArray(): Tool[] {
    const tools = getStaticTools();
    return Object.entries(tools).map(([id, tool]) => ({
        ...tool,
        id,
        votes: tool.votes || 0,
    })) as Tool[];
}

/**
 * Get tools filtered by a predicate function
 */
export function getToolsWhere(
    predicate: (tool: ApiTool, id: string) => boolean,
): Tool[] {
    const tools = getStaticTools();
    return Object.entries(tools)
        .filter(([id, tool]) => predicate(tool, id))
        .map(([id, tool]) => ({
            ...tool,
            id,
            votes: tool.votes || 0,
        })) as Tool[];
}

/**
 * Get tools for a specific language
 */
export function getToolsByLanguage(language: string): Tool[] {
    return getToolsWhere((tool) =>
        tool.languages.includes(language.toLowerCase()),
    );
}

/**
 * Get tools for a specific category
 */
export function getToolsByCategory(category: string): Tool[] {
    return getToolsWhere((tool) =>
        tool.categories.includes(category.toLowerCase()),
    );
}

/**
 * Get tools for a specific type
 */
export function getToolsByType(type: string): Tool[] {
    return getToolsWhere((tool) => tool.types.includes(type.toLowerCase()));
}

/**
 * Get total count of tools
 */
export function getToolsCount(): number {
    return Object.keys(getStaticTools()).length;
}
